#!/bin/bash

# Cadenza Quick Setup Script
# Makes it easy to get started with Cadenza

set -e  # Exit on any error

echo "🚀 Cadenza Quick Setup"
echo "====================="

# Check prerequisites
echo "📋 Checking prerequisites..."

# Check .NET
if ! command -v dotnet &> /dev/null; then
    echo "❌ .NET SDK not found. Please install .NET 8.0+ from https://dotnet.microsoft.com/download"
    exit 1
fi

DOTNET_VERSION=$(dotnet --version)
echo "✅ .NET SDK found: $DOTNET_VERSION"

# Build Cadenza
echo ""
echo "🔨 Building Cadenza transpiler..."
cd src
dotnet build
if [ $? -eq 0 ]; then
    echo "✅ Build successful!"
else
    echo "❌ Build failed. Please check the error messages above."
    exit 1
fi

cd ..

# Create cadenzac alias helper script
echo ""
echo "🔧 Creating helper script..."

FLOWLANG_ROOT=$(pwd)
HELPER_SCRIPT="$HOME/.cadenzac"

cat > "$HELPER_SCRIPT" << EOF
#!/bin/bash
# Cadenza Helper Script
# Auto-generated by setup.sh

dotnet run --project "$FLOWLANG_ROOT/src/Cadenza.Core/cadenzac-core.csproj" -- "\$@"
EOF

chmod +x "$HELPER_SCRIPT"

# Add to PATH suggestions
echo ""
echo "🎉 Setup complete!"
echo ""
echo "💡 To use Cadenza easily, add this alias to your shell profile:"
echo ""
echo "   echo 'alias cadenzac=\"$HELPER_SCRIPT\"' >> ~/.bashrc"
echo "   source ~/.bashrc"
echo ""
echo "   # OR for zsh:"
echo "   echo 'alias cadenzac=\"$HELPER_SCRIPT\"' >> ~/.zshrc"
echo "   source ~/.zshrc"
echo ""
echo "🧪 Test your installation:"
echo ""
echo "   # Create a test file"
echo '   echo "function main() -> string { return \"Hello, Cadenza!\" }" > test.cdz'
echo ""
echo "   # Run it (from this directory):"
echo "   dotnet run --project src/Cadenza.Core/cadenzac-core.csproj -- test.cdz test.cs"
echo "   dotnet run test.cs"
echo ""
echo "   # Or with alias (after setting it up):"
echo "   cadenzac test.cdz"
echo ""
echo "📚 Next steps:"
echo "   - Read the Getting Started guide: docs/getting-started.md"
echo "   - Try the examples in examples/"
echo "   - Create a new project: cadenzac new my-project"
echo ""
echo "Happy coding! 🎉"