#!/bin/bash

# FlowLang Quick Setup Script
# Makes it easy to get started with FlowLang

set -e  # Exit on any error

echo "🚀 FlowLang Quick Setup"
echo "====================="

# Check prerequisites
echo "📋 Checking prerequisites..."

# Check .NET
if ! command -v dotnet &> /dev/null; then
    echo "❌ .NET SDK not found. Please install .NET 8.0+ from https://dotnet.microsoft.com/download"
    exit 1
fi

DOTNET_VERSION=$(dotnet --version)
echo "✅ .NET SDK found: $DOTNET_VERSION"

# Build FlowLang
echo ""
echo "🔨 Building FlowLang transpiler..."
cd src
dotnet build
if [ $? -eq 0 ]; then
    echo "✅ Build successful!"
else
    echo "❌ Build failed. Please check the error messages above."
    exit 1
fi

cd ..

# Create flowc alias helper script
echo ""
echo "🔧 Creating helper script..."

FLOWLANG_ROOT=$(pwd)
HELPER_SCRIPT="$HOME/.flowc"

cat > "$HELPER_SCRIPT" << EOF
#!/bin/bash
# FlowLang Helper Script
# Auto-generated by setup.sh

dotnet run --project "$FLOWLANG_ROOT/src/flowc.csproj" -- "\$@"
EOF

chmod +x "$HELPER_SCRIPT"

# Add to PATH suggestions
echo ""
echo "🎉 Setup complete!"
echo ""
echo "💡 To use FlowLang easily, add this alias to your shell profile:"
echo ""
echo "   echo 'alias flowc=\"$HELPER_SCRIPT\"' >> ~/.bashrc"
echo "   source ~/.bashrc"
echo ""
echo "   # OR for zsh:"
echo "   echo 'alias flowc=\"$HELPER_SCRIPT\"' >> ~/.zshrc"
echo "   source ~/.zshrc"
echo ""
echo "🧪 Test your installation:"
echo ""
echo "   # Create a test file"
echo '   echo "function main() -> string { return \"Hello, FlowLang!\" }" > test.flow'
echo ""
echo "   # Run it (from this directory):"
echo "   dotnet run --project src/flowc.csproj -- run test.flow"
echo ""
echo "   # Or with alias (after setting it up):"
echo "   flowc run test.flow"
echo ""
echo "📚 Next steps:"
echo "   - Read the Getting Started guide: docs/getting-started.md"
echo "   - Try the examples in examples/"
echo "   - Create a new project: flowc new my-project"
echo ""
echo "Happy coding! 🎉"