// <auto-generated>
// This file was generated by the Cadenza compiler. Do not edit manually.

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

public class BlazorCounter : ComponentBase
{
    private int _currentCount = 0;

    private void IncrementCount()
    {
        _currentCount = _currentCount + 1;
        StateHasChanged();
    }

    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        builder.OpenElement(0, "div");
        
        builder.OpenElement(1, "h1");
        builder.AddContent(2, "Counter");
        builder.CloseElement();

        builder.OpenElement(3, "p");
        builder.AddContent(4, $"Current count: {_currentCount}");
        builder.CloseElement();

        builder.OpenElement(5, "button");
        builder.AddAttribute(6, "class", "btn btn-primary");
        builder.AddAttribute(7, "onclick", EventCallback.Factory.Create(this, IncrementCount));
        builder.AddContent(8, "Click me");
        builder.CloseElement();
        
        builder.CloseElement(); // div
    }
}