// <auto-generated>
// This file was generated by the Cadenza compiler. Do not edit manually.

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

public class ConditionalRender : ComponentBase
{
    private bool _isVisible = true;

    private void ToggleVisibility()
    {
        _isVisible = !_isVisible;
        StateHasChanged();
    }

    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        builder.OpenElement(0, "div");
        
        builder.OpenElement(1, "button");
        builder.AddAttribute(2, "onclick", EventCallback.Factory.Create(this, ToggleVisibility));
        builder.AddContent(3, "Toggle Visibility");
        builder.CloseElement();

        if (_isVisible)
        {
            builder.OpenElement(4, "p");
            builder.AddContent(5, "This text is visible.");
            builder.CloseElement();
        }
        else
        {
            builder.OpenElement(6, "p");
            builder.AddContent(7, "This text is hidden.");
            builder.CloseElement();
        }
        
        builder.CloseElement(); // div
    }
}