// <auto-generated>
// This file was generated by the Cadenza compiler. Do not edit manually.

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

public class ParentComponent : ComponentBase
{
    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        builder.OpenElement(0, "div");
        
        builder.OpenElement(1, "h2");
        builder.AddContent(2, "Parent Component");
        builder.CloseElement();

        builder.OpenComponent<GreetingChild>(3);
        builder.AddAttribute(4, "Message", "Hello from Parent!");
        builder.CloseComponent();
        
        builder.CloseElement(); // div
    }
}