// <auto-generated>
// This file was generated by the Cadenza compiler. Do not edit manually.

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using Microsoft.JSInterop;

public class Button : ComponentBase
{

    // Component Parameters
    [Parameter] public string text { get; set; } = default!;
    [Parameter] public string variant { get; set; } = default!;
    [Parameter] public bool disabled { get; set; } = default!;

    // Service Injections
    [Inject] private IJSRuntime DOMService { get; set; } = default!;

    // Event Handlers
    private void on_click()
    {
    }


    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        builder.OpenComponent<button>(0);
        builder.AddAttribute(1, "text", text);
        builder.AddAttribute(2, "class", ("btn btn-" + variant));
        builder.AddAttribute(3, "disabled", disabled);
        builder.CloseComponent();
    }
}


