// <auto-generated>
// This file was generated by the Cadenza compiler. Do not edit manually.

using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using Microsoft.JSInterop;

public class HelloWorld : ComponentBase
{

    // Component Parameters
    [Parameter] public string name { get; set; } = default!;

    // Component State
    private string _message = default!;
    private string _counter = default!;

    // Service Injections
    [Inject] private IJSRuntime DOMService { get; set; } = default!;

    // Component Lifecycle
    protected override async Task OnInitializedAsync()
    {
        on_mount_block(set_state(_message, "Component mounted!"));
    }

    // Event Handlers
    private void on_click()
    {
    }

    private void on_reset()
    {
    }


    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        builder.OpenComponent<container>(0);
        builder.AddAttribute(1, "class", "hello-world");
        builder.AddAttribute(2, "ChildContent", (RenderFragment)((builder2) => {
            builder.OpenComponent<heading>(0);
            builder.AddAttribute(1, "level", 1);
            builder.AddAttribute(2, "text", _message);
            builder.CloseComponent();
            builder.OpenComponent<button>(3);
            builder.AddAttribute(4, "text", "Click me");
            builder.AddAttribute(5, "on_click", handle_click);
            builder.CloseComponent();
            builder.OpenComponent<button>(6);
            builder.AddAttribute(7, "text", "Reset");
            builder.AddAttribute(8, "on_click", handle_reset);
            builder.CloseComponent();
        }));
        builder.CloseComponent();
    }
}


